# -*- coding: utf-8 -*-
"""한국어 분석 및 특성 추출.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BLeao5UNYF-yRPAwjXzp6rrGV0KJtgj9
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# apt-get update
# apt-get install g++ openjdk-8-jdk python-dev python3-dev
# pip3 install JPype1
# pip3 install konlpy

# Commented out IPython magic to ensure Python compatibility.
# JAVA_HOME 환경변수 설정하기

# %env JAVA_HOME "/usr/lib/jvm/java-8-openjdk-amd64"

# 분석하기

import csv
import json
import os
from konlpy.tag import Okt
import csv

# Okt 객체 생성
okt = Okt()

# data 폴더 경로 설정
data_folder = '/content/drive/MyDrive/csv'

# data 폴더 내의 파일 리스트 가져오기
file_list = os.listdir(data_folder)

# 감성 사전 파일 경로
sentiment_dict_file = '/content/drive/MyDrive/Colab Notebooks/sentiment_dictionary_saved.json'

# 감성 사전 로드
with open(sentiment_dict_file, 'r', encoding='utf-8') as file:
    sentiment_dictionary = json.load(file)

# 파일 리스트 출력
for i in range(len(file_list)):
    file_list[i] = os.path.join(data_folder, file_list[i])
file_list.sort()

results = []
for i in range(len(file_list)):
    with open(file_list[i], 'r', encoding='utf-8') as file:
        file_name_without_extension = os.path.split(file_list[i])[1]
        # print(file_name_without_extension)

        # 형태소 분석된 결과를 저장할 리스트와 변수 초기화
        analyzed_reviews = []

        # 리더 
        reader = file.readlines()

        # 리뷰들을 형태소 분석하여 리스트에 추가
        for row in reader:
            review = row  # 리뷰 컬럼
            morphs = okt.morphs(review)
            analyzed_reviews.append(morphs)

        # 형태소 분석된 결과를 활용한 감성 점수 계산
        review_Num = len(analyzed_reviews)
        sentiment_score = 0  # 초기 감성 점수
        neg_freq = 0 # 나쁜 말이 나온 수
        neg_val = 0
        pos_freq = 0 # 좋은 말이 나온 수
        pos_val = 0
        review_scores = []
        # 모든 분석된 리뷰들에 대해
        for review in analyzed_reviews:
            # 각 리뷰의 모든 형태소들에 대해
            for morph in review:
                review_score = 0
                # 만약 형태소가 사전에 있다면
                if morph in sentiment_dictionary:
                    
                    # 그 극성을 저장하기
                    tmp = sentiment_dictionary[morph]
                    # 나쁜 형태소가 나온 빈도
                    if tmp < 0:
                        neg_freq += 1
                        neg_val += tmp
                    # 좋은 형태소가 나온 빈도
                    elif tmp > 0:
                        pos_freq += 1
                        pos_val += tmp
                    review_score += tmp
                    sentiment_score += tmp

                if review_score != 0:
                    review_scores.append(review_score)
        # print(review_scores)
        # print('총 감성 점수:', sentiment_score)
        # print("pos: ", pos)
        # print("neg: ", neg)
        results.append((sentiment_score/review_Num, pos_freq/review_Num, pos_val/review_Num, neg_freq/review_Num, neg_val/review_Num))

import csv


# CSV 파일 경로
csv_file = '/content/drive/MyDrive/Colab Notebooks/results3.csv'

# CSV 파일에 데이터 쓰기
with open(csv_file, 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['sentiment_score', 'pos_freq', 'pos_val', 'neg_freq', 'neg_val'])  # 헤더 작성
    writer.writerows(results)  # 데이터 작성